name: Run Unit Tests using Jest

env:
  SIS_API_KEY: ${{ secrets.SIS_API_KEY }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  ATLAS_URI: ${{ secrets.ATLAS_URI }}
  PORT: ${{ secrets.PORT }}
  TEST_URI: ${{ secrets.TEST_URI }}

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm test
        with:
          env:
          

      
